"""config

Revision ID: 057843a1237f
Revises: 
Create Date: 2026-04-11 11:10:28.755802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057843a1237f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discover_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_used_model', sa.String(), nullable=False),
    sa.Column('preferred_theme', sa.String(), nullable=False),
    sa.Column('preferred_font', sa.String(), nullable=False),
    sa.Column('total_messages_sent', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_configs_user_id'), 'user_configs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('daily_quota', sa.Integer(), nullable=False, comment='Maximum API calls allowed per day'),
    sa.Column('daily_used', sa.Integer(), nullable=False, comment='Number of API calls used today'),
    sa.Column('last_reset', sa.Date(), nullable=False, comment='Date when daily quota was last reset'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Whether user has admin privileges'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Account creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_configs_user_id'), table_name='user_configs')
    op.drop_table('user_configs')
    op.drop_table('discover_news')
    # ### end Alembic commands ###
